version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/  
networks:
  internal:
    driver: bridge







# version: "3"
# services:
#   nginx:
#     build:
#       context: .
#       dockerfile: nginx/Dockerfile
#     ports: 
#       - "8080:80"
#     networks:
#       - internal
#     volumes:
#       - ./data/:/var/www/html/
#   php:
#     image: php:fpm-alpine
#     networks:
#       - internal
#     volumes:
#       - ./data/:/var/www/html/  
# networks:
#   internal:
#     driver: bridge